### ISSUE TITLE
If summary fails, don't show failure.

### ISSUE THREAD

**Issue by JulianNorton** [premgane/agolo-slackbot#11]
![screen shot 2016-04-18 at 1 43 48 pm](https://cloud.githubusercontent.com/assets/2412992/14613740/c81e61d2-056b-11e6-8b0f-6d029264ab67.png)

https://www.youtube.com/watch?v=IgMguikysAk

**Comment by premgane** [comment]
Fixed in 75ccdf19d8825570342e3400890d4306746abd45
