### ISSUE TITLE
Don't post summary if it's empty

### ISSUE THREAD

**Issue by agoloprem** [premgane/agolo-slackbot#17]
Example:

https://www.dropbox.com/s/8g09khe2mmovcxx/Screenshot%202016-04-29%2010.44.24.png?dl=0

**Comment by JulianNorton** [comment]
https://wiki.postgresql.org/images/b/b4/Pg-as-nosql-pgday-fosdem-2013.pdf too

**Comment by premgane** [comment]
Fixed in PR #18
